// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4PM_VxduHQOWRgQrvsEpqdiDJC9xwpQQ',
    appId: '1:978445495323:web:aa1d803554b0cd858f5cbe',
    messagingSenderId: '978445495323',
    projectId: 'ecommerce-importing-app',
    authDomain: 'ecommerce-importing-app.firebaseapp.com',
    storageBucket: 'ecommerce-importing-app.appspot.com',
    measurementId: 'G-074CXTS8BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhFDDEauMNM7YgKPuaU6zsk5_jVlvz1Yc',
    appId: '1:978445495323:android:fa2534cb76b7d3f28f5cbe',
    messagingSenderId: '978445495323',
    projectId: 'ecommerce-importing-app',
    storageBucket: 'ecommerce-importing-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGUYsZrURN6lPyjyAStTLX6d5caiTXWlg',
    appId: '1:978445495323:ios:8826cd9a065661378f5cbe',
    messagingSenderId: '978445495323',
    projectId: 'ecommerce-importing-app',
    storageBucket: 'ecommerce-importing-app.appspot.com',
    iosBundleId: 'com.example.importWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGUYsZrURN6lPyjyAStTLX6d5caiTXWlg',
    appId: '1:978445495323:ios:8826cd9a065661378f5cbe',
    messagingSenderId: '978445495323',
    projectId: 'ecommerce-importing-app',
    storageBucket: 'ecommerce-importing-app.appspot.com',
    iosBundleId: 'com.example.importWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4PM_VxduHQOWRgQrvsEpqdiDJC9xwpQQ',
    appId: '1:978445495323:web:e24b91fa236a69648f5cbe',
    messagingSenderId: '978445495323',
    projectId: 'ecommerce-importing-app',
    authDomain: 'ecommerce-importing-app.firebaseapp.com',
    storageBucket: 'ecommerce-importing-app.appspot.com',
    measurementId: 'G-DWB2HHE04Z',
  );
}
